### PR TITLE
Update to GCC 10.2

### PR DESCRIPTION
**Pull request by rleh**
...and build into `/opt/avr-gcc` instead of `/work/avr-gcc`.

### CODE REVIEW

**Review by salkinium — APPROVED** [review]
I like it, installing in /opt is a much, much better choice!

**Comment by salkinium** [comment]
You'll probably have to adapt some PATH's somewhere now though!

**Comment by rleh** [comment]
Here: https://github.com/modm-ext/docker-modm-build/blob/master/Dockerfile#L45

**Comment by salkinium** [comment]
Could you perhaps add a simple install instruction to the readme, so that people coming from the modm homepage don't get stuck.

**Comment by rleh** [comment]
> I like it, installing in `/opt` is a much, much better choice!

The idea is a result of your comment: https://github.com/modm-io/modm/pull/456#discussion_r481359362

I hope the compiled version is usable on other machines, let's try...

**Comment by rleh** [comment]
I've pushed ca7467e to master, a Dockerhub build already is running to update the _modm/avr-gcc-prerequisites_ container to Ubuntu 20.04.

Updated README will be pushed once Dockerhub is done.

**Pull request merged**
